export const styles ={
    "LoginRecoveryAuthnCodeConfig_Box_1": {},
    "LoginRecoveryAuthnCodeConfig_Box_2": {},
    "LoginRecoveryAuthnCodeConfig_Box_3": {},
    "LoginRecoveryAuthnCodeConfig_Typography_1": {},
    "LoginRecoveryAuthnCodeConfig_ListItem_1": {},
    "LoginRecoveryAuthnCodeConfig_Box_4": {},
    "LoginRecoveryAuthnCodeConfig_Button_1": {},
    "LoginRecoveryAuthnCodeConfig_Button_2": {},
    "LoginRecoveryAuthnCodeConfig_Button_3": {},
    "LoginRecoveryAuthnCodeConfig_Box_5": {},
    "LoginRecoveryAuthnCodeConfig_TextField_1": {},
    "LoginRecoveryAuthnCodeConfig_FormLabel_1": {},
    "LoginRecoveryAuthnCodeConfig_Box_6": {},
    "LoginRecoveryAuthnCodeConfig_TextField_2": {},
    "LoginRecoveryAuthnCodeConfig_TextField_3": {},
    "LoginRecoveryAuthnCodeConfig_TextField_4": {},
    "LoginRecoveryAuthnCodeConfig_TextField_5": {},
    "LoginRecoveryAuthnCodeConfig_Button_4": {},
    "LoginRecoveryAuthnCodeConfig_TextField_6": {},
    "LoginRecoveryAuthnCodeConfig_Box_7": {},
    "LoginRecoveryAuthnCodeConfig_Box_8": {},
    "LoginRecoveryAuthnCodeConfig_Box_9": {},
    "LoginRecoveryAuthnCodeConfig_FormLabel_2": {},
    "LoginRecoveryAuthnCodeConfig_TextField_7": {}
}