export const styles ={
    "Box_1": {},
    "Box_2": {},
    "Box_3": {},
    "Typography_1": {},
    "ListItem_1": {},
    "Box_4": {},
    "Button_1": {},
    "Button_2": {},
    "Button_3": {},
    "Box_5": {},
    "TextField_1": {},
    "FormLabel_1": {},
    "Box_6": {},
    "TextField_2": {},
    "TextField_3": {},
    "TextField_4": {},
    "TextField_5": {},
    "Button_4": {},
    "TextField_6": {},
    "Box_7": {},
    "FormLabel_2": {},
    "TextField_7": {}
}