export const styles ={
    "Box_1": {},
    "Box_2": {},
    "Button_1": {},
    "List_1": {},
    "ListItem_1": {},
    "Link_1": {},
    "Typography_1": {},
    "Box_3": {},
    "FormLabel_1": {},
    "Link_2": {},
    "Box_4": {},
    "Box_5": {},
    "Box_6": {},
    "Box_7": {},
    "Box_8": {},
    "Box_9": {},
    "TextField_1": {},
    "Link_3": {},
    "Box_10": {}
}